### ISSUE TITLE
Наследоваться надо от UIViewController, а не от ViewController

### ISSUE THREAD

**Issue by alexfilimon** [NikitaStudent/AccountingWater#1]
https://github.com/NikitaStudent/AccountingWater/blob/1d7a326b79b0ee8d9cd8d486e6e918c0294fbe0d/AccountingWater/Xib/MainViewController.swift#L12

Лично у меня ругается Xcode на это. Ну и плюс ничего полезного в классе ViewController нету

**Comment by nikita31k** [comment]
Сделано
