### ISSUE TITLE
Точно ли исползуется?

### ISSUE THREAD

**Issue by alexfilimon** [NikitaStudent/AccountingWater#10]
https://github.com/NikitaStudent/AccountingWater/blob/1d7a326b79b0ee8d9cd8d486e6e918c0294fbe0d/AccountingWater/Xib/CustomViewController.swift#L11

Если не используется, то можно удалить

**Comment by nikita31k** [comment]
я его доделал, теперь он работает, это для заполнения начального значения в ручную(вместо кнопок), я просто это еще не сделал push
