### ISSUE TITLE
Не make, а mark

### ISSUE THREAD

**Issue by alexfilimon** [NikitaStudent/AccountingWater#2]
https://github.com/NikitaStudent/AccountingWater/blob/1d7a326b79b0ee8d9cd8d486e6e918c0294fbe0d/AccountingWater/Xib/MainViewController.swift#L25

Почему именно MAKE? обычно пишут // MARK: - some text
Ну и плюс обычно пишут MARK для того, чтобы отделить части кода друг от друга - то есть в реализации класса. В методах пишут просто комменты

**Comment by nikita31k** [comment]
сделано, переделал в простые комментарии
