### ISSUE TITLE
Методы пишутся с маленькой буквы

### ISSUE THREAD

**Issue by alexfilimon** [NikitaStudent/AccountingWater#3]
https://github.com/NikitaStudent/AccountingWater/blob/1d7a326b79b0ee8d9cd8d486e6e918c0294fbe0d/AccountingWater/Xib/MainViewController.swift#L48

Все методы принято писать начиная с маленькой буквы. Даже IBAction

**Comment by NikitaStudent** [comment]
сделано

**Comment by nikita31k** [comment]
сделано
