### ISSUE TITLE
Подумать над неймингом

### ISSUE THREAD

**Issue by alexfilimon** [NikitaStudent/AccountingWater#7]
https://github.com/NikitaStudent/AccountingWater/blob/1d7a326b79b0ee8d9cd8d486e6e918c0294fbe0d/AccountingWater/Data/DataModel.swift#L10

Если это глобальный Стейт приложения, то надо бы назвать по-другому. Что такое Global не очень понятно. Я бы назвал лучше GlobalState

**Comment by nikita31k** [comment]
сделано
